//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Go.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GOTYPE                      129
#define IDD_board_size_dlg              130
#define IDR_MENU1                       131
#define IDD_DIALOG2                     133
#define IDD_DIALOG3                     134
#define IDD_BoardSize                   134
#define IDD_DIALOG1                     135
#define IDD_DIALOG4                     136
#define IDB_leftarrow1                  137
#define IDB_rightarrow1                 138
#define IDB_leftarrow2                  140
#define IDB_rightarrow2                 141
#define IDB_board0                      142
#define IDB_node_black                  143
#define IDB_node_white                  144
#define IDB_stones2                     145
#define IDB_BlackWhite_40               146
#define IDB_board_birch                 147
#define IDR_ReviewBoard                 153
#define IDB_BITMAP1                     157
#define IDB_Black_30                    158
#define IDB_White_30                    159
#define IDB_Mask_30                     160
#define IDB_Black_40                    161
#define IDB_White_40                    162
#define IDB_Black_59                    163
#define IDB_White_59                    164
#define IDB_Mask_40                     165
#define IDB_Mask_59                     166
#define IDD_PlayStatus                  167
#define IDB_cswang1                     168
#define IDB_cswang2                     169
#define IDB_BITMAP2                     170
#define IDB_Black                       171
#define IDB_Black_33                    172
#define IDB_White_33                    173
#define IDB_Mask_33                     174
#define IDB_Mask_36                     175
#define IDB_White_36                    176
#define IDB_Black_36                    177
#define IDB_Black_38                    178
#define IDB_White_38                    179
#define IDB_Mask_38                     180
#define IDR_StoneClick                  181
#define IDC_CURSOR1                     182
#define IDC_CURSOR2                     183
#define IDC_CURSOR3                     184
#define IDC_CURSOR4                     185
#define IDC_CURSOR5                     186
#define IDC_CURSOR6                     187
#define IDC_CURSOR7                     188
#define IDC_CURSOR8                     189
#define IDC_CURSOR9                     190
#define IDC_CURSOR10                    191
#define IDR_CountDown2                  194
#define IDR_CountDown3                  196
#define IDR_CountDown4                  197
#define IDR_CountDown5                  199
#define IDR_CountDown6                  200
#define IDR_CountDown7                  201
#define IDR_CountDown8                  202
#define IDR_CountDown9                  203
#define IDR_CountDown10                 204
#define IDR_CountDown1                  206
#define IDR_StartCountDown              208
#define IDR_FinalCountDown              210
#define IDR_RemainTwoCountDown          212
#define IDR_RemainThreeCountDown        214
#define IDR_StartTheGame                216
#define IDB_BITMAP3                     217
#define IDC_CURSOR_NoUse                218
#define IDB_BITMAP4                     219
#define IDB_Number9                     220
#define IDB_Number8                     221
#define IDB_Number7                     222
#define IDB_Number6                     223
#define IDB_Number5                     224
#define IDB_Number4                     225
#define IDB_Number3                     226
#define IDB_Number2                     227
#define IDB_Number1                     228
#define IDB_Number0                     229
#define IDC_RADIO1                      1003
#define IDC_RADIO2                      1004
#define IDC_RADIO3                      1005
#define IDC_BlackStone                  1010
#define IDC_WhiteStone                  1011
#define IDC_SystemDetermined            1012
#define IDC_Handicap                    1013
#define IDC_BasicTime                   1030
#define IDC_CountDownTime               1031
#define IDC_NumCountDown                1032
#define IDC_PSK                         1033
#define IDC_SSK                         1034
#define IDC_ChineseRule                 1035
#define IDC_JapanRule                   1036
#define IDC_Board19                     1037
#define IDC_Board13                     1038
#define IDC_Board9                      1039
#define IDC_IngRule                     1040
#define IDR_setting1                    32771
#define ID_MENUITEM32772                32772
#define ID_board_size                   32773
#define ID_forward_1                    32774
#define ID_forward_5                    32775
#define ID_backward_1                   32776
#define ID_backward_5                   32777
#define ID_to_the_end                   32778
#define ID_to_the_begin                 32779
#define ID_PlayStatus                   32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
